import os

_LOCAL_FILES = os.path.dirname(__file__)

BIOMED_407_ALLERGY_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.allergy.bsv')
BIOMED_407_CCDA_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.ccda.bsv')
BIOMED_407_DEMOGRAPHICS_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.demographics.bsv')
BIOMED_407_DIAGNOSIS_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.diagnosis.bsv')
BIOMED_407_ENCOUNTER_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.encounter.bsv')
BIOMED_407_IMMUNIZATION_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.immunization.bsv')
BIOMED_407_LAB_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.lab.bsv')
BIOMED_407_MEDICATION_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.medication.bsv')
BIOMED_407_OTHER_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.other.bsv')
BIOMED_407_PHYSICAL_EXAM_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.physical_exam.bsv')
BIOMED_407_PROBLEM_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.problem.bsv')
BIOMED_407_PROCEDURE_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.procedure.bsv')
BIOMED_407_SOCIAL_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.social.bsv')
BIOMED_407_TREATMENT_BSV = os.path.join(_LOCAL_FILES, 'BIOMED-407.treatment.bsv')
BIOMED_407_ALLERGY_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.allergy.json')
BIOMED_407_CCDA_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.ccda.json')
BIOMED_407_DEMOGRAPHICS_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.demographics.json')
BIOMED_407_DIAGNOSIS_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.diagnosis.json')
BIOMED_407_ENCOUNTER_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.encounter.json')
BIOMED_407_IMMUNIZATION_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.immunization.json')
BIOMED_407_LAB_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.lab.json')
BIOMED_407_MEDICATION_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.medication.json')
BIOMED_407_OTHER_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.other.json')
BIOMED_407_PHYSICAL_EXAM_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.physical_exam.json')
BIOMED_407_PROBLEM_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.problem.json')
BIOMED_407_PROCEDURE_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.procedure.json')
BIOMED_407_SOCIAL_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.social.json')
BIOMED_407_TREATMENT_JSON = os.path.join(_LOCAL_FILES, 'BIOMED-407.treatment.json')

