HEADER::= HEADER_UPPER | HEADER_TITLE | HEADER_COLON |  SUBHEADER_COLON | KEYVAL_COLON | KEYVAL_COLON_STRICT

HINT::= LIST | LIST_FIRST | LIST_HEADER | BLANKLINE | NEWLINE | BEGIN | COLON | UPPER_WORD | UPPER_WORD_COLON | TITLE_WORD | TITLE_WORD_COLON

HEADER_UPPER::= BEGIN UPPER_WORD_MAX10 SPACE? (COLON | NEWLINE) 
HEADER_TITLE::= BEGIN TITLE_WORD_MAX10 SPACE? (COLON | NEWLINE)
HEADER_COLON::= BEGIN (UPPER_WORD_MAX10|TITLE_WORD_MAX10) SPACE? COLON

SUBHEADER_COLON::= (UPPER_WORD_COLON_MAX3 | TITLE_WORD_COLON_MAX3) 
SUBHEADER_COLON_STRICT::= BEGIN SUBHEADER_COLON

KEYVAL_COLON::= SUBHEADER_COLON TEXT_WORD_MAX10
KEYVAL_COLON_STRICT::= SUBHEADER_COLON_STRICT TEXT_WORD_MAX3 ( NEWLINE| TAB| SPACE+)

LOWER::= '[a-z]'
UPPER::= '[A-Z]'

UPPER_WORD::= UPPER+
TITLE_WORD::= (UPPER LOWER+)

UPPER_WORD_MANY::= ( UPPER_WORD SPACE? )+
TITLE_WORD_MANY::= ( TITLE_WORD SPACE? )+

UPPER_WORD_MAX3::= (UPPER_WORD SPACE)? (UPPER_WORD SPACE)? UPPER_WORD
TITLE_WORD_MAX3::= (TITLE_WORD SPACE)? (TITLE_WORD SPACE)? TITLE_WORD

UPPER_WORD_MAX10::= (UPPER_WORD_MAX3 SPACE)? (UPPER_WORD_MAX3 SPACE)? (UPPER_WORD_MAX3 SPACE)? UPPER_WORD
TITLE_WORD_MAX10::= (TITLE_WORD_MAX3 SPACE)? (TITLE_WORD_MAX3 SPACE)? (TITLE_WORD_MAX3 SPACE)? TITLE_WORD

UPPER_WORD_COLON::= UPPER_WORD SPACE? COLON
TITLE_WORD_COLON::= TITLE_WORD SPACE? COLON

UPPER_WORD_COLON_MAX3::= UPPER_WORD_MAX3 SPACE? COLON
TITLE_WORD_COLON_MAX3::= TITLE_WORD_MAX3 SPACE? COLON

LIST_HEADER::= HEADER PAD DIGIT_LIST
LIST_FIRST::= NEWLINE PAD? '1' SPACE? DOT
LIST::= LIST1? (DIGIT_LIST DOT) | ('('? DIGIT_LIST ')')

NEWLINE::='\n'|'position is beginning of file, the first character'
BEGIN::=NEWLINE + PAD?
BLANKLINE::=BEGIN NEWLINE

COLON::=':'
DOT::='.'

VERTICAL_TAB::='\x0b'
FORM_FEED::='\x0c'
SPACE::=(' '|VERTICAL_TAB|FORM_FEED)

TAB::= '\t'|(SPACE SPACE SPACE SPACE)
PAD::= TAB|(SPACE? SPACE? SPACE? SPACE?)

ZERO::= '0'
DIGIT_POS::='1-9'
DIGIT::=DIGIT_POS | ZERO
DIGIT_LIST::= (DIGIT_POS DOT) | (DIGIT_POS DIGIT DOT)

ALPHANUM::= (LOWER|UPPER|DIGIT)
SEP::=('/'|':'|'-')

TEXT_WORD::= (ALPHANUM+SEP)+
TEXT_WORD_MAX3::=  (TEXT_WORD SPACE)? (TEXT_WORD SPACE)? TEXT_WORD
TEXT_WORD_MAX10::= (TEXT_WORD_MAX3 SPACE)? (TEXT_WORD_MAX3 SPACE)? (TEXT_WORD_MAX3 SPACE)? TEXT_WORD
